### ISSUE TITLE
New colony incompatible with Visual Studio 2019

### ISSUE THREAD

**Issue by buffstop** [AntMeNet/AntMeClassic#10]
Creating a new colony in C# and opening it in Visual Studio 2019, Visual Studio claims its incompatible. I found no way to migrate / fix it.

Visual Studio Express C# 2010 is able to open and run it.

**Comment by tomwendel** [comment]
So with the latest PR I verified that the templates still run with most current VS versions. So I guess the original source of this problem was a missing "Workload" of the installed Visual Studio. It's required to have the Desktop Development part installed to run AntMe!. So lets refer to #31 and close this one.
